// @generated by `cargo run -p shape-coverage -- --write-fixture`. Do not edit.
//
// One row per opaque `shapes.rs` declares, included by `hostile.rs`'s
// `reclaim_table`. Derived for the reason the fixture is: a hand-kept list
// beside a generated set is a list that goes stale on the next regeneration.
[
    ("ShapeConfinedSB", g::frustrate_drop_ShapeConfinedSB as Reclaim),
    ("ShapeConfinedSA", g::frustrate_drop_ShapeConfinedSA as Reclaim),
    ("ShapeConfinedDynB", g::frustrate_drop_ShapeConfinedDynB as Reclaim),
    ("ShapeConfinedDynA", g::frustrate_drop_ShapeConfinedDynA as Reclaim),
    ("ShapeResidentSB", g::frustrate_drop_ShapeResidentSB as Reclaim),
    ("ShapeResidentSA", g::frustrate_drop_ShapeResidentSA as Reclaim),
    ("ShapeResidentDynB", g::frustrate_drop_ShapeResidentDynB as Reclaim),
    ("ShapeResidentDynA", g::frustrate_drop_ShapeResidentDynA as Reclaim),
    ("ShapeFrozenSB", g::frustrate_drop_ShapeFrozenSB as Reclaim),
    ("ShapeFrozenSA", g::frustrate_drop_ShapeFrozenSA as Reclaim),
    ("ShapeFrozenDynB", g::frustrate_drop_ShapeFrozenDynB as Reclaim),
    ("ShapeFrozenDynA", g::frustrate_drop_ShapeFrozenDynA as Reclaim),
    ("ShapeLockedSB", g::frustrate_drop_ShapeLockedSB as Reclaim),
    ("ShapeLockedSA", g::frustrate_drop_ShapeLockedSA as Reclaim),
    ("ShapeLockedDynB", g::frustrate_drop_ShapeLockedDynB as Reclaim),
    ("ShapeLockedDynA", g::frustrate_drop_ShapeLockedDynA as Reclaim),
]
