// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.6.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Sync, scalars only. The cheapest thing FRB can generate.
int add({required int a, required int b}) =>
    RustLib.instance.api.crateApiSimpleAdd(a: a, b: b);

/// Sync, String in and out.
String greet({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name);

/// Sync, a Vec<u8> argument (the wire-heavy case).
BigInt sumBytes({required List<int> data}) =>
    RustLib.instance.api.crateApiSimpleSumBytes(data: data);

Point translate({required Point p, required double dx, required double dy}) =>
    RustLib.instance.api.crateApiSimpleTranslate(p: p, dx: dx, dy: dy);

/// Async (FRB's default), so the generated code carries the handler path.
Future<int> doubleSlowly({required int x}) =>
    RustLib.instance.api.crateApiSimpleDoubleSlowly(x: x);

/// A stream, so the generated code carries a StreamSink.
Stream<int> tick({required int n}) =>
    RustLib.instance.api.crateApiSimpleTick(n: n);

/// A typed error, so the generated code carries the anyhow/Result path.
Future<int> checkedDiv({required int a, required int b}) =>
    RustLib.instance.api.crateApiSimpleCheckedDiv(a: a, b: b);

/// A mirrored struct, so the generated Dart carries a class and the
/// generated Rust carries a CST encode/decode pair.
class Point {
  final double x;
  final double y;

  const Point({
    required this.x,
    required this.y,
  });

  @override
  int get hashCode => x.hashCode ^ y.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Point &&
          runtimeType == other.runtimeType &&
          x == other.x &&
          y == other.y;
}
